#!/usr/bin/env node
/**
 * Rebuild pm2-core Wasm and embed bytes for the single-file Vite bundle.
 * Requires: rustc/cargo (wasm32-unknown-unknown), wasm-bindgen CLI matching Cargo.toml.
 */
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const crate = path.join(root, "wasm", "pm2-core");
const wasmOut = path.join(crate, "target", "wasm32-unknown-unknown", "release", "pm2_core.wasm");
const pkgDir = path.join(root, "src", "wasm", "pkg");
const bytesTs = path.join(root, "src", "wasm", "pm2CoreBytes.ts");

function run(cmd, cwd = root, extraEnv = {}) {
  console.log(`$ ${cmd}`);
  execSync(cmd, {
    cwd,
    stdio: "inherit",
    shell: true,
    env: { ...process.env, ...extraEnv },
  });
}

run("cargo test --manifest-path wasm/pm2-core/Cargo.toml");
run(
  "cargo build --manifest-path wasm/pm2-core/Cargo.toml --target wasm32-unknown-unknown --release",
  root,
  { RUSTFLAGS: "-C target-feature=+simd128" },
);

fs.mkdirSync(pkgDir, { recursive: true });
run(
  `wasm-bindgen --target web --out-dir "${pkgDir}" --out-name pm2_core "${wasmOut}"`,
);

const wasmPath = path.join(pkgDir, "pm2_core_bg.wasm");
let wasm = fs.readFileSync(wasmPath);

try {
  execSync("wasm-opt -version", { stdio: "ignore" });
  run(`wasm-opt -O --enable-bulk-memory -o "${wasmPath}" "${wasmPath}"`);
  wasm = fs.readFileSync(wasmPath);
  console.log(`wasm-opt → ${wasm.length} bytes`);
} catch {
  console.log("wasm-opt not found; using wasm-bindgen output as-is");
}

fs.writeFileSync(
  bytesTs,
  `// Generated by pnpm wasm:build — do not edit.\nexport const PM2_CORE_WASM_BASE64 =\n  ${JSON.stringify(wasm.toString("base64"))};\n`,
);
console.log(`embedded ${wasm.length} wasm bytes → ${path.relative(root, bytesTs)}`);

// Prevent Vite from emitting a .wasm sidecar via `new URL(..., import.meta.url)`.
const jsPath = path.join(pkgDir, "pm2_core.js");
let js = fs.readFileSync(jsPath, "utf8");
js = js.replace(
  /if \(typeof module_or_path === 'undefined'\) \{\s*module_or_path = new URL\('pm2_core_bg\.wasm', import\.meta\.url\);\s*\}/,
  `if (typeof module_or_path === 'undefined') {
        throw new Error('pm2_core: pass WebAssembly.Module or bytes (single-file embed)');
    }`,
);
fs.writeFileSync(jsPath, js);
console.log("patched pm2_core.js to avoid URL wasm fetch");
